### ISSUE TITLE
Beautifulsoap yükleme hatasi

### ISSUE THREAD

**Issue by semaf** [erdemarslan/namazvakti-Python#1]
Hayirli aksamlar,

Hocam, Python 2.7.13 da "beautifulsoap" kütüphanesi yüklemesinde hata veriyor ve onun yerine "beautfilsoap4" yüklenmesini istiyor.

`"You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."`

Ancak bu kütüphande yüklenmis olsada "bs4" modülü bulunmuyor.
```
python ornek.py 
Traceback (most recent call last):
  File "ornek.py", line 2, in <module>
    from namazvakti import namazvakti
  File "/home/pi/namazvakti-Python/namazvakti.py", line 6, in <module>
    from bs4 import BeautifulSoup4
ImportError: No module named bs4
```
EDIT:
Hata pip komutunun python 2.7 yüklü olmasina ragmen, python 3.6 kabul etmesi.

**Comment by PythonMehmet** [comment]
Sorunun çözümünü buldunuz mu hocam

**Comment by semaf** [comment]
Cok vakit gecti ve kod mevcut degil maalesef.
